version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - johanneshiry
  assignees:
  - johanneshiry
  ignore:
  - dependency-name: org.scalatest:scalatest_2.13
    versions:
    - ">= 3.3.a, < 3.4"
  - dependency-name: com.diffplug.spotless
    versions:
    - 5.11.1
    - 5.12.0
  - dependency-name: org.scalatest:scalatest_2.13
    versions:
    - 3.2.7
